In [76]:
import numpy as np

**Valid Sudoku**

In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [14]:
row=np.sum(s,axis=1)
row
for i in row:
    if i == 45:
        print("for row its valid")
        break
    else:
        print("not valid")

for row its valid


In [15]:
coloumn=np.sum(s,axis=0)
coloumn
for i in coloumn:
    if i == 45:
        print("for coloumn its valid")
        break
    else:
        print("not valid")

for coloumn its valid


In [19]:
slice=s[0:3,0:3]
slice

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [27]:
siu=slice.sum()
siu


np.int64(45)

In [29]:
for i in slice:
    if siu==45:
        print("suduko")
        break
    else:
        print("try again")

suduko


In [39]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=(s[i:i+3,j:j+3])
        sum_all=(n.sum())
        print(sum_all)
        if sum_all==45:
            print("suduko")
            break
        else:
            print("try again")

45
suduko
45
suduko
45
suduko


**General Questions**

In [59]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [43]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [44]:
#Find the average age of students.
np.mean(data[:,0])

np.float64(18.4)

In [47]:
#Extract Math marks of all students.
print(data[:,1])

[85 92 76 65 90]


In [49]:
#Find the highest Science mark.
np.max(data[:,2])

np.int64(95)

In [63]:
#Get details of the student who scored more than 90 in Math.

data[data[:,1]>90]

array([[19, 92, 88]])

In [57]:
#Increase Math marks of all students by 5.
(data[:,1])+5
data

array([90, 97, 81, 70, 95])

In [74]:
#Find how many students are younger than 19.
len(data[data[:,0]<19])

3

In [73]:
#Calculate the average marks in each subject (column-wise mean).
maths=np.mean(data[:,1])
science=np.mean(data[:,2])
print(f"you are avg marks in maths is {maths} your avg marks in science {science}")

you are avg marks in maths is 81.6 your avg marks in science 83.2


In [80]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [85]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])