In [1]:
import numpy as np

In [18]:
arr=np.arange(1,20)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [4]:
arr[1:9]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr_slice=arr[3::2]
arr_slice

array([ 4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr[[1,1]]

array([[ 6,  7,  8,  9, 10],
       [ 6,  7,  8,  9, 10]])

In [10]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [16]:
arr[0,0]

np.int64(1)

In [20]:
arr[0,4]

np.int64(5)

In [21]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [27]:
slice_2d=arr[0:2,1:3]

In [28]:
slice_2d

array([[2, 3],
       [7, 8]])

In [29]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [31]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [33]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [34]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

In [35]:
arr[3:,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [36]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

In [41]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
bool_index =arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [43]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [46]:
a1=np.array([1,2,3,4,5])

In [47]:
a2=np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [48]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [4]:
arr

array([1, 2, 3, 4])

In [6]:
arr.sum()


np.int64(10)

In [9]:
np.arange(1,31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [8]:
np.resize(6,5)

array([6, 6, 6, 6, 6])

In [12]:
arr=np.arange(1,31).reshape(6,5)

In [13]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [14]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])
a1+a2

array([ 7,  9, 11, 13, 15])

In [15]:
l=[10,20,30,40]
arr=np.array(l)

In [16]:
for i in l:
    print(i+10)

20
30
40
50


In [17]:
arr+10

array([20, 30, 40, 50])

In [27]:
arr=np.arange(1,21)

In [19]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [21]:
slice=arr[:5]
slice

array([1, 2, 3, 4, 5])

In [23]:
slice_1=slice*10
slice_1

array([10, 20, 30, 40, 50])

In [24]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
b=arr.copy()#no changes
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
import numpy as np

In [31]:
arr=np.array

In [33]:
arr=np.arange(1,31)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [35]:
arr+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [36]:
slice=arr[:5]

array([1, 2, 3, 4, 5])

In [37]:
slice+2

array([101,   4,   5,   6,   7])

In [45]:
print("welcome to the game ")
print("guess the number")
arr=np.random.randint(1,4)
print("your are random number is",arr)
a=int(input("enter the number"))
if arr==a:
    print("you won")
else:
    print("sorry try again")
    


welcome to the game 
guess the number
your are random number is 3


enter the number 3


you won


In [46]:
arr=np.arange(1,10)

In [47]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr.resize(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr1
arr2

array([[5, 6],
       [7, 8]])

In [52]:
arr1

array([[1, 2],
       [3, 4]])

In [53]:
arr1@arr2

array([[19, 22],
       [43, 50]])

In [55]:
np.dot(arr1,arr2)

array([[19, 22],
       [43, 50]])

In [56]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
arr1

array([[1, 2],
       [3, 4]])

In [60]:
arr1.T

array([[1, 3],
       [2, 4]])

In [61]:
arr1

array([[1, 2],
       [3, 4]])

In [63]:
A=np.array([1,2,3,4])
B=np.array([5,6,7,8])
A

array([1, 2, 3, 4])

In [64]:
B

array([5, 6, 7, 8])

In [65]:
np.vstack((A,B))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [66]:
np.hstack((A,B))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [67]:
np.column_stack((A,B))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [74]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
np.split(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]