In [1]:
print("hello")

hello


In [2]:
def hello():
    print("how are you")

In [3]:
hello()

how are you


In [1]:
print("hello sir")

hello sir


In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np
print(np.__version__)


2.3.5


In [6]:
pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [4]:
print("hello")

hello


In [8]:
import numpy as np

In [9]:

arr=np.array([1,2,3,4])

In [10]:
arr

array([1, 2, 3, 4])

In [15]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [17]:
sharu=np.array([1,2,3,4])
sharu

array([1, 2, 3, 4])

In [18]:
np.array(sharu)

array([1, 2, 3, 4])

In [19]:
meow=np.array(["sharath",1,3.5])
meow

array(['sharath', '1', '3.5'], dtype='<U32')

In [20]:
np.array(meow)

array(['sharath', '1', '3.5'], dtype='<U32')

In [21]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:

siu=np.arange(1,11)
siu

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
siu=np.zeros((6,6))
siu

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
siu=np.zeros(6)
siu

array([0., 0., 0., 0., 0., 0.])

In [32]:
np.ones(1)

array([1.])

In [33]:
np.ones(2)

array([1., 1.])

In [34]:
arr=np.linspace(1,5,2)

In [35]:
arr

array([1., 5.])

In [38]:
arr=np.linspace(1,2,3)
arr

array([1. , 1.5, 2. ])

In [39]:
arr=np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
random generative function


In [1]:
print("hello")

hello


In [2]:
import numpy as np

In [4]:
arr=np.random.rand(1,5)
arr

array([[7.21001076e-02, 6.68884777e-04, 1.66886865e-01, 9.29992796e-01,
        6.26279499e-01]])

In [5]:
arr=np.random.randint(10,20,10)
arr

array([14, 15, 16, 10, 13, 14, 19, 13, 18, 16], dtype=int32)

In [8]:
n=10
if n>9:
    print("great")
else:
    print("super")

great


In [14]:
print("welcome to the game")
a=int(input("enter a number"))
b=np.random.randint(1,5)
print("the random number is",b)

if a==b:
    print("you won")
else:
    print("you failes but try agian good luck")

welcome to the game


enter a number 2


the random number is 2
you won


In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr.shape

(3, 3)

In [20]:
arr.size

9

In [21]:
arr.dtype

dtype('int64')

In [22]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr.min()


np.int64(1)

In [25]:
arr.max()

np.int64(9)

In [26]:
arr.sum()

np.int64(45)

In [27]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [28]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

In [29]:
arr.mean()

np.float64(5.0)

In [30]:
arr.std()

np.float64(2.581988897471611)

In [31]:
arr.argmax()

np.int64(8)

In [32]:
arr.argmin()

np.int64(0)

In [37]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [38]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])